# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d55d777e34c427d60f059bc3a657a192c56ffc55b818e869432d5e429c02b37c29b827b20616b0ac49f7bbd1bb4ac66499e4ef2b9b7d82751f2a2b435c950b1

test:
  secret_key_base: 325681d95706f26d6f25f10734a51247b0886e8c296c8e55573db0e33c7ac8d63e100fcbae835bf8d226769fd404c41c959d129affdf36fcfcdc9541a97d8381

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
