# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c0c0b8c678d728af3a649985179b5dfb64657a2ec9f4746cc93a6331c325f93cc78653548187d4a24e34efb5c364b65add828b3c5054e39a40b048a5edc8abe

test:
  secret_key_base: 9cc3b74c7b4ede5dc48d7ccbcec54ff4dec00d0ddafd045f2901b36953719fecc1b7de4947244ac2d614fa3361a8fe6baca9b96726e4e97f5dfa7b794be0464d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
